name: Run prechecks
on: [push]
jobs:
  Run-All-Prechecks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Execute checks
        run: |
          make docker-all-checks
